export const GET_ALL_TRAILS_SUCCESS = 'GET_ALL_TRAILS_SUCCESS'
export const GET_ALL_TRAILS_ERROR = 'GET_ALL_TRAILS_ERROR'
export const ADD_TRAIL_SUCCESS = 'ADD_TRAIL_SUCCESS'
export const ADD_TRAIL_ERROR = 'ADD_TRAIL_ERROR'
